# Generated by Django 3.0.3 on 2020-03-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200306_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numbder',
            new_name='number',
        ),
    ]
